import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8002/workspaces');
  await page.getByText('default').click();
  await page.getByTestId('action-button').click();
  await page.getByTestId('gateway-service-url-input').click();
  await page.getByTestId('gateway-service-url-input').fill('https://api.kong-air.com/flights');
  await page.getByTestId('advanced-fields-collapse').getByTestId('collapse-trigger-content').click();
  await page.getByTestId('gateway-service-retries-input').click();
  await page.getByTestId('gateway-service-retries-input').click();
  await page.getByTestId('gateway-service-retries-input').click();
  await page.getByTestId('gateway-service-retries-input').click();
  await page.getByTestId('gateway-service-retries-input').fill('-6');
  await page.getByTestId('gateway-service-retries-input').click();
  await page.getByTestId('gateway-service-retries-input').fill('-9');
  await page.getByTestId('gateway-service-retries-input').click();
  await page.getByTestId('gateway-service-retries-input').fill('0');
  await page.getByTestId('gateway-service-retries-input').click();
  await page.getByTestId('gateway-service-retries-input').fill('127');
  await page.getByTestId('gateway-service-connTimeout-input').click();
  await page.getByTestId('gateway-service-retries-input').fill('133');
  await page.getByTestId('gateway-service-connTimeout-input').click();
  await page.getByTestId('gateway-service-connTimeout-input').click();
  await page.getByTestId('gateway-service-connTimeout-input').click();
  await page.getByTestId('gateway-service-connTimeout-input').click();
  await page.getByTestId('gateway-service-connTimeout-input').click();
  await page.getByTestId('gateway-service-connTimeout-input').fill('6000');
  await page.getByText('Service endpointDefine where this service should send requests.Full URL Define').click();
  await page.getByTestId('gateway-service-writeTimeout-input').click();
  await page.getByTestId('gateway-service-writeTimeout-input').click();
  await page.getByTestId('gateway-service-writeTimeout-input').click();
  await page.getByTestId('gateway-service-writeTimeout-input').click();
  await page.getByTestId('gateway-service-writeTimeout-input').fill('6000');
  await page.getByTestId('gateway-service-readTimeout-input').click();
  await page.getByTestId('gateway-service-readTimeout-input').fill('6000');
  await page.getByTestId('gateway-service-clientCert-input').click();
  await page.getByTestId('gateway-service-clientCert-input').fill('thisisaid');
  await page.getByTestId('gateway-service-ca-certs-input').click();
  await page.getByTestId('gateway-service-ca-certs-input').fill('thisisacerti');
  await page.getByTestId('gateway-service-ca-certs-input').click();
  await page.getByTestId('gateway-service-ca-certs-input').click();
  await page.getByTestId('gateway-service-ca-certs-input').press('ArrowLeft');
  await page.getByTestId('gateway-service-ca-certs-input').press('ArrowLeft');
  await page.getByTestId('gateway-service-ca-certs-input').press('ArrowLeft');
  await page.getByTestId('gateway-service-ca-certs-input').press('ArrowLeft');
  await page.getByTestId('gateway-service-tls-verify-checkbox').check();
  await page.locator('div').filter({ hasText: /^True$/ }).first().click();
  await page.getByTestId('gateway-service-name-input').click();
  await page.getByTestId('gateway-service-name-input').fill('myfirstservice');
  await page.getByTestId('tags-collapse').getByTestId('collapse-trigger-content').click();
  await page.getByTestId('gateway-service-tags-input').click();
  await page.getByTestId('gateway-service-tags-input').fill('1');
  await page.getByTestId('service-create-form-submit').click();
  await page.getByTestId('gateway-service-clientCert-input').click();
  await page.getByTestId('gateway-service-clientCert-input').fill('');
  await page.getByTestId('service-create-form-submit').click();
  await page.getByTestId('gateway-service-ca-certs-input').click();
  await page.getByTestId('gateway-service-ca-certs-input').click();
  await page.getByTestId('gateway-service-ca-certs-input').fill('');
  await page.getByTestId('gateway-service-ca-certs-input').click();
  await page.getByTestId('gateway-service-clientCert-input').click();
  await page.getByTestId('gateway-service-clientCert-input').fill('a3d2f4b6-91e7-4b9c-bc2f-6e3e0e8b4a71');
  await page.getByTestId('gateway-service-ca-certs-input').click();
  await page.getByTestId('gateway-service-ca-certs-input').fill('7c98e320-3fa4-4cb7-90f2-5a6f8dbf91c9');
  await page.getByText('Service endpointDefine where this service should send requests.Full URL Define').click();
  await page.getByTestId('service-create-form-submit').click();
  await page.getByTestId('gateway-service-clientCert-input').click();
  await page.getByTestId('gateway-service-clientCert-input').press('ControlOrMeta+c');
  await page.getByTestId('gateway-service-clientCert-input').click();
  await page.getByTestId('gateway-service-clientCert-input').press('ControlOrMeta+a');
  await page.getByTestId('gateway-service-clientCert-input').fill('');
  await page.getByTestId('service-create-form-submit').click();
  await page.getByTestId('service-routes').click();
  await page.getByTestId('show-service').click();
  await page.getByTestId('select-config-format').click();
  await page.getByRole('button', { name: 'JSON' }).click();
  await page.getByTestId('code-block-copy-button-json-codeblock').click();
  await page.getByText('{ "protocol": "https", "').click();
  await page.getByTestId('select-config-format').click();
  await page.getByRole('button', { name: 'YAML' }).click();
  await page.getByTestId('select-config-format').click();
  await page.getByRole('button', { name: 'Structured' }).click();
  await page.getByTestId('name-plain-text').click();
  await page.getByTestId('updated_at-date').click();
  await page.getByTestId('created_at-date').click();
  await page.getByTestId('kong-ui-app-layout-main').getByRole('link', { name: 'Gateway Services' }).click();
  await page.getByTestId('row-actions-dropdown-trigger').click();
  await page.getByTestId('action-entity-copy-id').click();
  await page.getByTestId('row-actions-dropdown-trigger').click();
  await page.getByTestId('action-entity-view').click();
});